### ISSUE TITLE
host is required but specified

### ISSUE THREAD

**Issue by gregf** [ftpgrab/ftpgrab#45]
ftpgrab freebsd 64bit binary from the 5.1.0 release. Two issues.

First I get this even though host is defined in sftp.

Fri, 15 Feb 2019 00:23:38 UTC FTL Improper configuration error="host is required"

ftpgrab --version reprots "dev" instead of the actual version number.

**Comment by crazy-max** [comment]
@gregf Can you post your config ull config file please ?

**Comment by gregf** [comment]
```
server:
  type: sftp
  sftp:
    host: example.com
    port: 22
    username: gregf
    password:
    key: /home/gregf/.ssh/id_ed25519
    sources: /home/gregf/downloads/tv
    timeout: 30
    max_packet_size: 32768
db:
  enable: true
  path: /home/gregf/.ftpgrab/tv.db

download:
  output: /mnt/media/tv/unsorted
  uid: 1001
  gid: 1001
  chmod_file: 0644
  chmod_dir: 0755
  include:
  exclude:
  since: 0001-01-01T00:00:00Z
  retry: 3
  hide_skipped: false
  create_basedir: false

mail:
  enable: false
  host: localhost
  port: 25
  ssl: false
  insecure_skip_verify: false
  username:
  password:
  from:
  to:
```

**Comment by crazy-max** [comment]
Sources is a slice :

```
server:
  type: sftp
  sftp:
    host: example.com
    port: 22
    username: gregf
    password:
    key: /home/gregf/.ssh/id_ed25519
    sources:
      - /home/gregf/downloads/tv
    timeout: 30
    max_packet_size: 32768

db:
  enable: true
  path: /home/gregf/.ftpgrab/tv.db

download:
  output: /mnt/media/tv/unsorted
  uid: 1001
  gid: 1001
  chmod_file: 0644
  chmod_dir: 0755
  include:
  exclude:
  since: 0001-01-01T00:00:00Z
  retry: 3
  hide_skipped: false
  create_basedir: false

mail:
  enable: false
  host: localhost
  port: 25
  ssl: false
  insecure_skip_verify: false
  username:
  password:
  from:
  to:
```
