### ISSUE TITLE
Skip download when path contain character like "[" and "]"

### ISSUE THREAD

**Issue by mickael-bertrand** [ftpgrab/ftpgrab#49]
Hi :) 

### Behaviour

Downloads are not started when parent folder name contain brackets as a character **[** or **]**

#### Steps to reproduce this issue

1. create folder with brackets caracter like **[** or **]**, for example directory.**[**team**]**/filename.mkv
2. grabftp list the file, send the command, but do not start download 
3. configure disable_epsv: true 

#### Expected behaviour

```
Tue, 30 Apr 2019 09:30:21 UTC INF Never downloaded
Tue, 30 Apr 2019 09:30:21 UTC INF Downloading file (993.4MB) to /path/filename...
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.209 #1 was ready
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.209 #1 sending command TYPE I
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.232 #1 got 200-TYPE is now 8-bit binary
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.232 #1 sending command SIZE /path/filename
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.256 #1 got 213-993427745
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.257 #1 was ready
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.257 #1 was ready
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.257 #1 sending command TYPE I
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.280 #1 got 200-TYPE is now 8-bit binary
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.280 #1 sending command PASV
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.304 #1 got 227-Entering Passive Mode (@ip)
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.305 #1 opening data connection to @IP
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.328 #1 upgrading data connection to TLS
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.329 #1 sending command RETR /path/filename
Tue, 30 Apr 2019 09:30:21 UTC DBG goftp: 3.351 #1 got 150-Accepted data connection
970144.3 kbytes to download
```

#### Actual behaviour

```
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.237 #1 opening data connection to @ip
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.263 #1 upgrading data connection to TLS
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.263 #1 sending command MLSD /path[team]/filename
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.287 #1 got 150-Accepted data connection
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.337 #1 was ready
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.337 #1 sending command PASV
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.360 #1 got 227-Entering Passive Mode (@ip)
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.360 #1 opening data connection to @IP
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.382 #1 upgrading data connection to TLS
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.382 #1 sending command MLSD /path[team]/filename
Tue, 30 Apr 2019 09:18:52 UTC DBG goftp: 1.404 #1 got 150-Accepted data connection
```

no download are started

### Configuration

* FTPGrab version  : 5.2.0
* Platform : linux mint
* Remote  server: Pure-FTPd

### Logs
in step before

### configuration : 

```yml
server:
  type: ftp
  ftp:
    host: xxxxxxxxxx
    port: 21
    username: XXXXXX
    password: XXXXXX
    sources:
      - /path
    timeout: 5
    disable_epsv: true
    tls:
      enable: yes
      implicit: false
      insecure_skip_verify: true
    log_trace: true

db:
  enable: true
  path: ftpgrab.db

download:
  output: /path
  uid:
  gid:
  chmod_file: 0755
  chmod_dir: 0755
  since:
  retry: 3
  hide_skipped: false
  create_basedir: false
```

Thanks, :)
