### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by ADRFranklin** [ftpgrab/ftpgrab#83]
#### Steps to reproduce this issue

1. Pull docker image
2. Run docker image 
3. Get an error about "Cannot connect to server"

#### Expected behaviour

> Tell me what should happen
I expect that I should be able to connect to the ftp server

#### Actual behaviour

> Tell me what happens instead
{"level":"fatal","error":"dial tcp: i/o timeout","time":"2020-06-17T14:34:22+01:00","message":"Cannot connect to server"}

### Configuration

* FTPGrab version (5.0.0) : ftpgrab/ftpgrab:latest (5.0)
* Platform (windows/linux/freebsd/macos) : linux
* System info (type `uname -a`) : Linux xxx.xxx.xxx 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Remote FTP (Pure-FTPd) or SFTP (OpenSSH) server: Pure-FTPd

### Logs

> FTPGrab logs (set --log-level flag to debug and --log-ftp)
```
Wed, 17 Jun 2020 14:46:36 BST INF Starting FTPGrab edge


Wed, 17 Jun 2020 14:46:36 BST DBG {


  "Cli": {


    "Version": false,


    "Cfgfile": "/ftpgrab.yml",


    "Schedule": "*/30 * * * *",


    "Timezone": "Europe/London",


    "LogLevel": "debug",


    "LogJSON": false,


    "LogFile": ""


  },


  "App": {


    "ID": "ftpgrab",


    "Name": "FTPGrab",


    "Desc": "Grab your files periodically from a remote FTP or SFTP server easily",


    "URL": "https://ftpgrab.github.io",


    "Author": "CrazyMax",


    "Version": "edge"


  },


  "Server": {


    "Type": "ftp",


    "FTP": {


      "Host": "xxx",


      "Port": 10105,


      "Username": "********",


      "Password": "********",


      "Sources": [


        "/torrents/completed"


      ],


      "Timeout": 10000000000,


      "DisableEPSV": false,


      "TLS": false,


      "InsecureSkipVerify": false,


      "LogTrace": true


    },


    "SFTP": {


      "Host": "",


      "Port": 22,


      "Username": "********",


      "Password": "********",


      "Key": "********",


      "Sources": null,


      "Timeout": 30,


      "MaxPacketSize": 32768


    }


  },




{


    "Enable": true,


    "Path": "/db/ftpgrab.db"


  },


  "Download": {


    "Output": "/download",


    "UID": 0,


    "GID": 0,


    "ChmodFile": 420,


    "ChmodDir": 493,


    "Include": null,


    "Exclude": null,


    "Since": "0001-01-01T00:00:00Z",


    "Retry": 3,


    "HideSkipped": false,


    "CreateBasedir": false


  },


  "Notif": {


    "Mail": {


      "Enable": false,


      "Host": "localhost",


      "Port": 25,


      "SSL": false,


      "InsecureSkipVerify": false,


      "Username": "********",


      "Password": "********",


      "From": "",


      "To": ""


    },


    "Slack": {


      "Enable": false,


      "WebhookURL": ""


    },


    "Webhook": {


      "Enable": false,


      "Endpoint": "",


      "Method": "GET",


      "Headers": {},


      "Timeout": 10000000000


    }


  }


}
{"level":"fatal","error":"dial tcp: i/o timeout","time":"2020-06-17T14:34:22+01:00","message":"Cannot connect to server"}
```

Just to note, that I am perfectly able to connect to the ftp server using the standard ftp utility on Linux. I am even able to connect on a Windows machine, but I checked more then once, over the credentials and can ensure you that all the information passed in to the config is correct.

I use docker daily, and I haven't experienced connections not being able to reach the target. Unfortunately the container ends before I am able to enter it to see if I could poke around the issue, but unfortunately that is not possible.

I have removed the host address from the logs.

```
  ftpgrab:
    image: ftpgrab/ftpgrab:latest
    container_name: ftpgrab
    volumes:
      - "${DATA_DIR:?required}/ftpgrab/db:/db:rw"
      - "${MOUNT_DIR?required}:/download:rw"
      - "${DATA_DIR:?required}/ftpgrab/ftpgrab.yml:/ftpgrab.yml:ro"
    environment:
      - "TZ=Europe/London"
      - "SCHEDULE=*/30 * * * *"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
    restart: always     
```

I have also tried the `edge` version of the docker image, to no luck.

**Comment by crazy-max** [comment]
@ADRFranklin 

> FTPGrab version (5.0.0) : ftpgrab/ftpgrab:latest (5.0)

Please use latest stable release: **6.4.0**

> Remote FTP (Pure-FTPd) or SFTP (OpenSSH) server: Pure-FTPd

Which version of Pure-FTPd? Can you give me server logs?

> {"level":"fatal","error":"dial tcp: i/o timeout","time":"2020-06-17T14:34:22+01:00","message":"Cannot connect to server"}

Looks like the container cannot reach your FTP server at `xxx:10105`
What's the output of `ftp xxx 10105`?

**Comment by ADRFranklin** [comment]
@crazy-max I did mention, that I was able to connect to the ftp server using `ftp <hostname> <port>` just fine.

```
root@remote-02:~/mount# ftp xxx 10105
Connected to xxx.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 50 allowed.
220-Local time is now 14:43. Server port: 21.
220-This is a private system - No anonymous login
220 You will be disconnected after 15 minutes of inactivity.
```

**Comment by crazy-max** [comment]
@ADRFranklin Looking at those logs, your local port is `21`. Is it a Pure-FTPd standalone server or a container binded to `10105`? Also it looks like you're using explicit SSL on your server. Can you try this config:

```yaml
server:
  ftp:
    host: xxx
    port: 10105
    username: ********
	password: ********
    sources:
      - /
    timeout: 5
    disable_epsv: false
    tls: false
    insecure_skip_verify: true
    log_trace: true
```

And also use **ftpgrab/ftpgrab:6.4.0**. Thanks

**Comment by ADRFranklin** [comment]
Errors from ftpgrab
```
Wed, 17 Jun 2020 16:02:35 BST INF Starting FTPGrab 6.4.0


Wed, 17 Jun 2020 16:02:35 BST FTL Cannot load configuration error="unable to decode into struct, yaml: unmarshal errors:\n  line 9: cannot unmarshal !!int `5` into time.Duration"
```

Config:
```
server:
  ftp:
    host: xxx
    port: 10105
    username: xxx
    password: xxx
    sources:
      - /
    timeout: 5
    disable_epsv: false
    tls: false
    insecure_skip_verify: true
    log_trace: true
```

Docker:
```
  ftpgrab:
    image: ftpgrab/ftpgrab:6.4.0.
    container_name: ftpgrab
    volumes:
      - "${DATA_DIR:?required}/ftpgrab/db:/db:rw"
      - "${TORRENT_DIR}:/download:rw"
      - "${DATA_DIR:?required}/ftpgrab/ftpgrab.yml:/ftpgrab.yml:ro"
    environment:
      - "TZ=Europe/London"
      - "SCHEDULE=*/30 * * * *"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
    restart: always    
```
