### ISSUE TITLE
Access denide

### ISSUE THREAD

**Issue by Alexzanderk** [ftpgrab/ftpgrab#88]
### Behaviour
Create folder
#### Steps to reproduce this issue

1. start docker container
2. use `promise-ftp`
3. create folder via `promise-ftp`

#### Expected behaviour
create a folder  

#### Actual behaviour

error access denided

### Configuration
```
server:
  type: ftp
  ftp:
    host: test.rebex.net
    port: 21
    username: demo
    password: password
    sources:
      - /
    timeout: 5s
    disable_epsv: false
    tls: false
    insecure_skip_verify: false
    log_trace: false

db:
  enable: true

download:
  uid: 0
  gid: 0
  chmod_file: 777
  chmod_dir: 777
  include:
  exclude:
  since: 0001-01-01T00:00:00Z
  retry: 3
  hide_skipped: false
  create_basedir: false

notif:
  mail:
    enable: false
    host: smtp.example.com
    port: 587
    ssl: false
    insecure_skip_verify: false
    username: webmaster@example.com
    password: apassword
    from: ftpgrab@example.com
    to: webmaster@example.com
  webhook:
    enable: false
    endpoint: http://webhook.foo.com/sd54qad89azd5a
    method: GET
    headers:
      Content-Type: application/json
      Authorization: Token123456
    timeout: 10s
```
* FTPGrab version (6.4.0 ) : 6.4.0  latest
* Platform (**macos**) :  **macos**
* Remote **FTP** (Pure-FTPd) or SFTP (OpenSSH) server: **FTP**

### Error screenshot 

![image](https://user-images.githubusercontent.com/16296369/86648450-8b164880-bfe9-11ea-902a-e09c72742db8.png)

## Code typescript for reproduce
```
import Client = require('promise-ftp');

interface IFtpClient {
  ftpClient: Client;

  createDir: (path: string, folderName: string) => void;
  removeDir: () => void;
  readDir: (path: string) => void;
  changeFile: () => void;
  readFile: () => void;
  writeFile: () => void;
  removeFile: () => void;

  connect: () => void;
  end: () => void;
}

export class FtpClient implements IFtpClient {
  ftpClient: Client;
  options: Client.Options;

  constructor(options: Client.Options) {
    if (!options) {
      throw new Error('Ftp client options not found');
    }

    this.options = options;

    this.init();
  }

  init(): void {
    this.ftpClient = new Client();
  }

  async connect() {
    return await this.ftpClient.connect(this.options);
  }

  end() {
    return this.ftpClient.end();
  }

  async removeDir() {}

  async readFile() {}

  async writeFile() {}

  async removeFile() {}

  async createDir(path: string, folderName: string) {
    return this.ftpClient.mkdir(`${path}/${folderName}`);
  }

  async changeFile() {
    return this.ftpClient
      .put('foo.txt', 'fuu.txt')
      .then((d) => {
        console.log(d);
      })
      .catch((err) => {
        console.log(err);
      });
  }

  async readDir(path: string = '') {
    return this.ftpClient.list(path);
  }
}

const ftp = new FtpClient({
  host: 'test.rebex.net',
  port: 21,
  user: 'demo',
  password: 'password',
});

const main = async () => {
  const connect = await ftp.connect();
  const list = await ftp.readDir('/');
  console.log('test');
  const dir = await ftp.createDir('/', 'testDir').catch(err => {
    console.log(err);
    
  });
  console.log(dir)

  ftp.end();
};

main();

```

### package.json
```
{
  "name": "ftp_docker",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@types/promise-ftp": "^1.3.4",
    "ftp": "^0.3.10",
    "promise-ftp": "^1.3.5",
    "ts-node-dev": "^1.0.0-pre.49",
    "typescript": "^3.9.5"
  },
  "devDependencies": {
    "@types/ftp": "^0.3.31",
    "@types/node": "^14.0.14",
    "ts-node": "^8.10.2"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

### tsconfig.json
```
{
    "compilerOptions": {
        "target": "ES2017",
        "moduleResolution": "node",
        "module": "commonjs",
        "declaration": false,
        "sourceMap": true,
        "noImplicitReturns": false,
        "noImplicitUseStrict": false,
        "outDir": "./dist",
        "listFiles": false,
        "rootDir": ".",
        "noImplicitAny": true,
        "esModuleInterop": true,
        "typeRoots": ["ftp.d.ts"]
    },
    "include": ["./**/*", "test"],
    "exclude": ["node_modules", "test"],
    "compileOnSave": false
}

```
